TYPE=VIEW
query=select `U`.`name` AS `name`,`U`.`phone` AS `phone`,`U`.`address` AS `address`,`x`.`g_name` AS `g_name`,`G`.`g_icon` AS `g_icon`,`G`.`g_type` AS `g_type`,`x`.`uid` AS `uid`,`x`.`gid` AS `gid`,`x`.`total` AS `total`,`y`.`non` AS `non` from ((((select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `total` from `spin`.`user_gifts` group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`) `X` left join (select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `non` from `spin`.`user_gifts` where `spin`.`user_gifts`.`status` = 0 group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`) `Y` on(`x`.`gid` = `y`.`gid` and `x`.`uid` = `y`.`uid` and `x`.`g_name` = `y`.`g_name`)) join `spin`.`users` `U` on(`x`.`uid` = `U`.`uid`)) join `spin`.`gifts` `G` on(`G`.`gid` = `x`.`gid`))
md5=802fdf295087ab87e8832d6e9b803eb8
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2020-10-15 13:24:13
create-version=2
source=select `U`.`name` AS `name`,`U`.`phone` AS `phone`,`U`.`address` AS `address`,`X`.`g_name` AS `g_name`,`G`.`g_icon` AS `g_icon`,`G`.`g_type` AS `g_type`,`X`.`uid` AS `uid`,`X`.`gid` AS `gid`,`X`.`total` AS `total`,`Y`.`non` AS `non` from ((((select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `total` from `spin`.`user_gifts` group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`) `X` left join (select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `non` from `spin`.`user_gifts` where `spin`.`user_gifts`.`status` = 0 group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`) `Y` on(`X`.`gid` = `Y`.`gid` and `X`.`uid` = `Y`.`uid` and `X`.`g_name` = `Y`.`g_name`)) join `spin`.`users` `U` on(`X`.`uid` = `U`.`uid`)) join `spin`.`gifts` `G` on(`G`.`gid` = `X`.`gid`))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `U`.`name` AS `name`,`U`.`phone` AS `phone`,`U`.`address` AS `address`,`x`.`g_name` AS `g_name`,`G`.`g_icon` AS `g_icon`,`G`.`g_type` AS `g_type`,`x`.`uid` AS `uid`,`x`.`gid` AS `gid`,`x`.`total` AS `total`,`y`.`non` AS `non` from ((((select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `total` from `spin`.`user_gifts` group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`) `X` left join (select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `non` from `spin`.`user_gifts` where `spin`.`user_gifts`.`status` = 0 group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`) `Y` on(`x`.`gid` = `y`.`gid` and `x`.`uid` = `y`.`uid` and `x`.`g_name` = `y`.`g_name`)) join `spin`.`users` `U` on(`x`.`uid` = `U`.`uid`)) join `spin`.`gifts` `G` on(`G`.`gid` = `x`.`gid`))
mariadb-version=100413
